apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    user: $PV_DB_USER
    url: http://influxdb:8086
    basicAuth: true
    jsonData:
      dbName: $PV_DB_NAME
      httpMode: GET
    secureJsonData:
      password: $PV_DB_PASSWORD
